
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build React App
      run: npm run build
      
    - name: Prepare Directory Structure
      run: |
        echo "Préparation de la structure pour Infomaniak..."
        
        # Créer une structure temporaire pour organiser les fichiers
        mkdir -p temp_deploy
        
        # Copier les fichiers buildés dans le répertoire temporaire
        cp -R dist/* temp_deploy/ || true
        
        # Copier les autres fichiers nécessaires
        # API et ses sous-dossiers
        mkdir -p temp_deploy/api/config
        mkdir -p temp_deploy/api/controllers
        mkdir -p temp_deploy/api/middleware
        mkdir -p temp_deploy/api/models
        mkdir -p temp_deploy/api/models/traits
        mkdir -p temp_deploy/api/operations
        mkdir -p temp_deploy/api/utils
        
        # Copier tous les fichiers PHP et autres fichiers de l'API
        cp -R api/*.php temp_deploy/api/
        cp -R api/config/* temp_deploy/api/config/ || true
        cp -R api/controllers/* temp_deploy/api/controllers/ || true
        cp -R api/middleware/* temp_deploy/api/middleware/ || true
        cp -R api/models/* temp_deploy/api/models/ || true
        cp -R api/operations/* temp_deploy/api/operations/ || true
        cp -R api/utils/* temp_deploy/api/utils/ || true
        
        # Copier les fichiers cachés
        cp -R api/.htaccess temp_deploy/api/ || true
        cp -R api/.user.ini temp_deploy/api/ || true
        cp .htaccess temp_deploy/ || true
        
        # Vérifier et créer le .htaccess dans api/config
        if [ -f "api/config/.htaccess" ]; then
          cp api/config/.htaccess temp_deploy/api/config/
        else
          echo "# Interdire l'accès à ce répertoire
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
</IfModule>" > temp_deploy/api/config/.htaccess
        fi
        
        # Copier les uploads
        mkdir -p temp_deploy/public/lovable-uploads
        cp -R public/lovable-uploads/* temp_deploy/public/lovable-uploads/ || true
        
        echo "Structure temporaire créée avec succès"
        
    - name: Debug Directory Structure
      run: |
        echo "Structure finale avant déploiement:"
        ls -la temp_deploy/
        echo "Structure API:"
        ls -la temp_deploy/api/
        echo "Structure API Config:"
        ls -la temp_deploy/api/config/
        
    - name: Sync files to Infomaniak server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./temp_deploy/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          tsconfig*.json
          *.log
        log-level: verbose
        timeout: 120000
        dry-run: false

    - name: Post-deployment verification
      run: |
        echo "Déploiement terminé. Vérification de la structure:"
        curl -v "https://qualiopi.ch/" || echo "Vérification du site échouée"
        curl -v "https://qualiopi.ch/api/diagnostic.php" || echo "Vérification de l'API échouée"

