
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Message de déploiement'
        required: false
        default: 'Déploiement manuel'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: List dist content for debugging
      run: |
        echo "==== Listing dist directory ===="
        ls -la dist/
        echo "==== Listing dist/assets directory ===="
        ls -la dist/assets/

    # Étape 1: Créer les répertoires principaux d'abord
    - name: Create main directories
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          mkdir -p assets
          mkdir -p api
          mkdir -p public
          echo "=== Root directories created ==="
          ls -la

    # Étape 2: Créer les sous-répertoires de api
    - name: Create api subdirectories
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          mkdir -p api/config
          mkdir -p api/controllers
          mkdir -p api/middleware
          mkdir -p api/models
          mkdir -p api/operations
          mkdir -p api/utils
          echo "=== API subdirectories created ==="
          ls -la api/

    # Étape 3: Créer les sous-sous-répertoires
    - name: Create deeper subdirectories
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          mkdir -p api/models/traits
          mkdir -p public/lovable-uploads
          echo "=== Deep subdirectories created ==="
          ls -la api/models/

    # Étape 4: Déployer le contenu avec une vitesse réduite pour éviter les erreurs
    - name: Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        dangerous-clean-slate: false
        protocol: ftp
        port: 21
        timeout: 360000  # Augmenté à 6 minutes
        server-dir: "./"
        log-level: "verbose"
        max-concurrent-transfers: 4  # Réduire le nombre de transferts simultanés
