
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build React App
      run: npm run build
      
    - name: Prepare API Directory
      run: |
        echo "Préparation du répertoire API..."
        mkdir -p dist/sites/qualiopi.ch/api
        
        # Copier tous les fichiers de l'API
        cp -R api/* dist/sites/qualiopi.ch/api/
        
        # Copier les fichiers cachés (.htaccess, .user.ini, etc.)
        cp -R api/.htaccess dist/sites/qualiopi.ch/api/ || true
        cp -R api/.user.ini dist/sites/qualiopi.ch/api/ || true
        
        # Créer les sous-répertoires nécessaires
        mkdir -p dist/sites/qualiopi.ch/api/config
        mkdir -p dist/sites/qualiopi.ch/api/controllers
        mkdir -p dist/sites/qualiopi.ch/api/middleware
        mkdir -p dist/sites/qualiopi.ch/api/models
        mkdir -p dist/sites/qualiopi.ch/api/utils
        
    - name: Debug API Directory Structure
      run: |
        echo "Structure du répertoire API:"
        tree dist/sites/qualiopi.ch/api || ls -R dist/sites/qualiopi.ch/api
        
    - name: Sync full dist folder to Infomaniak server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          tsconfig*.json
          *.log
        log-level: verbose
        timeout: 120000
        dry-run: false

    - name: Post-deployment verification
      run: |
        echo "Déploiement terminé. Vérification de la structure:"
        curl -v "https://qualiopi.ch/api/diagnostic.php" || echo "Vérification de l'API échouée"
