
name: Build Application

on:
  push:
    branches: [ main ]  # Déclenche le workflow quand il y a un push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug - List files
      run: ls -la
      
    - name: Install dependencies
      run: npm ci
    
    - name: Debug - Node and NPM versions
      run: |
        node -v
        npm -v
    
    - name: Build project
      run: npm run build
      
    - name: Debug - List build output
      run: |
        echo "Contenu du répertoire dist :"
        ls -la dist || echo "Le répertoire dist n'existe pas"
        echo "Contenu du répertoire api :"
        ls -la api || echo "Le répertoire api n'existe pas"
    
    - name: Check if .htaccess exists
      run: |
        if [ -f .htaccess ]; then
          echo ".htaccess trouvé"
        else
          echo ".htaccess non trouvé - création d'un fichier vide"
          touch .htaccess
        fi
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          dist
          api
          .htaccess
