
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Message de déploiement'
        required: false
        default: 'Déploiement manuel'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: List dist content for debugging
      run: |
        echo "==== Listing dist directory ===="
        ls -la dist/
        echo "==== Listing dist/assets directory ===="
        ls -la dist/assets/

    # Étape 1: Créer tous les répertoires nécessaires sur le serveur
    - name: Create directories on server via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          mkdir -p assets
          mkdir -p api
          mkdir -p api/config
          mkdir -p api/controllers
          mkdir -p api/middleware
          mkdir -p api/models
          mkdir -p api/models/traits
          mkdir -p api/operations
          mkdir -p api/utils
          mkdir -p public
          mkdir -p public/lovable-uploads
          ls -la

    # Étape 2: Vérifier que les répertoires ont été créés correctement
    - name: Verify directories
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          echo "=== Listing root directory ==="
          ls -la
          echo "=== Listing api directory ==="
          ls -la api
          echo "=== Listing api/config directory ==="
          ls -la api/config

    # Étape 3: Déployer le contenu du dossier dist avec une configuration FTP standard
    - name: Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        dangerous-clean-slate: false
        protocol: ftp
        port: 21
        timeout: 240000
        server-dir: "./"
        log-level: "verbose"
