
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]  # ou 'master' selon votre branche principale
  workflow_dispatch:    # Permet le déclenchement manuel depuis l'interface GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build React App
      run: npm run build
      
    - name: Copy additional files
      run: |
        cp .htaccess dist/ || echo "No .htaccess file found"
        mkdir -p dist/api
        cp api/.htaccess dist/api/ || echo "No api/.htaccess file found"
        mkdir -p dist/api/config
        cp api/.user.ini dist/api/ || echo "No api/.user.ini file found"
        mkdir -p dist/public
        cp -r public/lovable-uploads dist/public/ || echo "No lovable-uploads directory found"
        
    - name: List build directory
      run: ls -la dist/
      
    - name: Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          tsconfig*.json
          src/**
        log-level: verbose
