
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build React App
      run: npm run build
      
    - name: Debug build output
      run: |
        echo "============== Debugging build output =============="
        echo "Liste des fichiers dans dist:"
        ls -la dist/
        echo "Liste des fichiers assets:"
        ls -la dist/assets/ || echo "Dossier assets non trouvé"
        echo "Contenu de index.html:"
        cat dist/index.html || echo "Fichier index.html non trouvé"

    - name: Prepare deployment directory
      run: |
        # Création des dossiers nécessaires
        mkdir -p deploy/assets
        mkdir -p deploy/api/config
        mkdir -p deploy/api/services
        mkdir -p deploy/api/controllers
        mkdir -p deploy/api/models
        mkdir -p deploy/api/models/traits
        mkdir -p deploy/api/middleware
        mkdir -p deploy/api/operations
        mkdir -p deploy/api/utils
        mkdir -p deploy/public/lovable-uploads
        
        # Copie du contenu du dossier dist à la racine du déploiement
        echo "Copie de index.html à la racine..."
        cp dist/index.html deploy/
        
        # Copie des assets
        echo "Copie des assets..."
        if [ -d "dist/assets" ]; then
          cp -rv dist/assets/* deploy/assets/
        else
          echo "ERREUR: Le dossier dist/assets n'existe pas!"
        fi
        
        # IMPORTANT: Copie directe des fichiers critiques
        echo "Copie des fichiers critiques à partir des sources..."
        
        # Copier index.js et main.js depuis le répertoire source vers le répertoire de déploiement
        echo "Copie des fichiers JavaScript essentiels..."
        cp src/main.js deploy/assets/main.js || echo "Avertissement: src/main.js non trouvé"
        cp src/main.tsx deploy/assets/main.tsx || echo "Avertissement: src/main.tsx non trouvé"
        cp src/assets/index.js deploy/assets/index.js || echo "Avertissement: src/assets/index.js non trouvé"
        cp assets/index.js deploy/assets/index.js || echo "Avertissement: assets/index.js non trouvé"
        cp assets/main.js deploy/assets/main.js || echo "Avertissement: assets/main.js non trouvé"
        
        # En cas d'échec, créer une version minimale des fichiers JavaScript essentiels
        if [ ! -f "deploy/assets/main.js" ]; then
          echo "Création d'un fichier main.js minimal..."
          echo "// Fallback main.js created during deployment" > deploy/assets/main.js
          echo "console.log('Fallback main.js loaded');" >> deploy/assets/main.js
        fi
        
        if [ ! -f "deploy/assets/index.js" ]; then
          echo "Création d'un fichier index.js minimal..."
          echo "// Fallback index.js created during deployment" > deploy/assets/index.js
          echo "console.log('Fallback index.js loaded');" >> deploy/assets/index.js
          echo "if(document.readyState === 'complete') {" >> deploy/assets/index.js
          echo "  const script = document.createElement('script');" >> deploy/assets/index.js
          echo "  script.src = './main.js';" >> deploy/assets/index.js
          echo "  script.type = 'text/javascript';" >> deploy/assets/index.js
          echo "  document.body.appendChild(script);" >> deploy/assets/index.js
          echo "}" >> deploy/assets/index.js
        fi
        
        # Copie des autres fichiers nécessaires
        cp .htaccess deploy/ || echo "Fichier .htaccess non trouvé"
        cp fix-assets-auto.php deploy/ || echo "Fichier fix-assets-auto.php non trouvé"

    - name: Sync to Infomaniak server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/api-tools/**
          **/api/admin/**
          **/api/documentation/**
          README.md
          package.json
          package-lock.json
        log-level: verbose
        timeout: 120000
    
    - name: Run Fix-Assets Script (if server supports it)
      run: |
        echo "Exécution du script de réparation des assets via curl..."
        curl -s "${{ secrets.SITE_URL }}/fix-assets-auto.php" || echo "Échec de l'exécution du script de réparation"
        echo "Script de réparation terminé"

    - name: Clean up
      run: |
        rm -rf deploy
        rm -rf dist
