
name: Déploiement Unifié vers Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Raison du déploiement manuel'
        required: false
        default: 'Déploiement manuel'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configuration de Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Installation des dépendances
      run: npm install --legacy-peer-deps
      
    - name: Construction de l'application React
      run: npm run build
      
    - name: Préparation du déploiement
      run: |
        echo "=== Déploiement Simplifié vers Infomaniak ==="
        echo "Date: $(date)"
        
        # Création du dossier de déploiement
        mkdir -p deploy
        
        # Copie DIRECTE du dossier dist
        cp -r dist/* deploy/ 2>/dev/null || echo "Attention: Dossier dist non trouvé"
        
        # Copier les fichiers racine essentiels
        cp index.php deploy/ 2>/dev/null || echo "index.php introuvable dans racine"
        cp index.html deploy/ 2>/dev/null || cp dist/index.html deploy/ 2>/dev/null || echo "ERREUR: index.html non trouvé"
        cp .htaccess deploy/ 2>/dev/null || echo "Attention: .htaccess non trouvé"
        
        # Copier le script de création de structure
        cp fix-directory-structure.php deploy/ 2>/dev/null || echo "Fichier fix-directory-structure.php non trouvé"
        
        # Configuration de la base de données
        mkdir -p deploy/api/config
        echo '{
            "host": "p71x6d.myd.infomaniak.com",
            "db_name": "p71x6d_richard",
            "username": "p71x6d_richard",
            "password": "Trottinette43!"
        }' > deploy/api/config/db_config.json
        
        # Configuration PHP
        echo '<?php
// Configuration des variables d'environnement pour Infomaniak
define("DB_HOST", "p71x6d.myd.infomaniak.com");
define("DB_NAME", "p71x6d_richard");
define("DB_USER", "p71x6d_richard");
define("DB_PASS", "Trottinette43!");
define("API_BASE_URL", "/api");
define("APP_ENV", "production");

// Fonction d'aide pour récupérer les variables d'environnement
function get_env($key, $default = null) {
    $const_name = strtoupper($key);
    if (defined($const_name)) {
        return constant($const_name);
    }
    return $default;
}
?>' > deploy/api/config/env.php
        
        # Créer .htaccess pour l'API
        mkdir -p deploy/api
        echo "# Activer la réécriture d'URL
RewriteEngine On

# Configuration CORS
Header set Access-Control-Allow-Origin \"*\"
Header set Access-Control-Allow-Methods \"GET, POST, OPTIONS, PUT, DELETE\"
Header set Access-Control-Allow-Headers \"Content-Type, Authorization, X-Requested-With\"

# Rediriger toutes les requêtes vers index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php [QSA,L]" > deploy/api/.htaccess
        
        # Vérifier ce qui a été préparé
        echo ""
        echo "=== Structure du déploiement ==="
        find deploy -type f | sort

    - name: Synchronisation vers le serveur Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/api-tools/**
          README.md
        log-level: verbose
        timeout: 120000

    - name: Nettoyage
      run: rm -rf deploy
