
name: Simple Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Raison du déploiement manuel'
        required: false
        default: 'Déploiement manuel'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build React App
      run: npm run build
      
    - name: Debug build output
      run: |
        echo "============== Debugging build output =============="
        echo "Liste des fichiers générés:"
        ls -la dist/
        ls -la dist/assets/ || echo "Dossier assets non trouvé"
        
    - name: Execute deployment script
      run: |
        chmod +x deploy-simple.sh
        ./deploy-simple.sh
        
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployment-files
        path: deploy/
        retention-days: 1
        
    - name: Copy dist directory to deployment
      run: |
        mkdir -p deploy/dist
        cp -r dist/* deploy/
        echo "Contenu du dossier deploy après copie du dist:"
        ls -la deploy/
      
    - name: Create required directories to prevent FTP errors
      run: |
        mkdir -p deploy/api/documentation
        echo "# API Documentation" > deploy/api/documentation/README.md
        echo "Vérification des répertoires créés:"
        ls -la deploy/api/
        
        # Création du fichier env.php avec les informations correctes
        mkdir -p deploy/api/config
        echo "<?php" > deploy/api/config/env.php
        echo "// Configuration des variables d'environnement pour Infomaniak" >> deploy/api/config/env.php
        echo "define('DB_HOST', 'p71x6d.myd.infomaniak.com');" >> deploy/api/config/env.php
        echo "define('DB_NAME', 'p71x6d_richard');" >> deploy/api/config/env.php
        echo "define('DB_USER', 'p71x6d_richard');" >> deploy/api/config/env.php
        echo "define('DB_PASS', 'Trottinette43!');" >> deploy/api/config/env.php
        echo "define('API_BASE_URL', '/api');" >> deploy/api/config/env.php
        echo "define('APP_ENV', 'production');" >> deploy/api/config/env.php
        echo "" >> deploy/api/config/env.php
        echo "// Fonction d'aide pour récupérer les variables d'environnement" >> deploy/api/config/env.php
        echo "function get_env(\$key, \$default = null) {" >> deploy/api/config/env.php
        echo "    \$const_name = strtoupper(\$key);" >> deploy/api/config/env.php
        echo "    if (defined(\$const_name)) {" >> deploy/api/config/env.php
        echo "        return constant(\$const_name);" >> deploy/api/config/env.php
        echo "    }" >> deploy/api/config/env.php
        echo "    return \$default;" >> deploy/api/config/env.php
        echo "}" >> deploy/api/config/env.php
        echo "" >> deploy/api/config/env.php
        echo "// Alias pour compatibilité avec différentes syntaxes" >> deploy/api/config/env.php
        echo "if (!function_exists('env')) {" >> deploy/api/config/env.php
        echo "    function env(\$key, \$default = null) {" >> deploy/api/config/env.php
        echo "        return get_env(\$key, \$default);" >> deploy/api/config/env.php
        echo "    }" >> deploy/api/config/env.php
        echo "}" >> deploy/api/config/env.php
        echo "?>" >> deploy/api/config/env.php
        
        # Création de db_config.json
        echo '{' > deploy/api/config/db_config.json
        echo '    "host": "p71x6d.myd.infomaniak.com",' >> deploy/api/config/db_config.json
        echo '    "db_name": "p71x6d_richard",' >> deploy/api/config/db_config.json
        echo '    "username": "p71x6d_richard",' >> deploy/api/config/db_config.json
        echo '    "password": "Trottinette43!"' >> deploy/api/config/db_config.json
        echo '}' >> deploy/api/config/db_config.json
      
    - name: FTP Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
        log-level: verbose
        timeout: 120000
        
    - name: Verify critical files after deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          cd /sites/qualiopi.ch/
          echo "=== Vérification post-déploiement ==="
          [ -f "api/.htaccess" ] && echo "✅ api/.htaccess: PRÉSENT" || echo "❌ api/.htaccess: MANQUANT"
          [ -f "api/config/env.php" ] && echo "✅ api/config/env.php: PRÉSENT" || echo "❌ api/config/env.php: MANQUANT"
          [ -f "api/config/db_config.json" ] && echo "✅ api/config/db_config.json: PRÉSENT" || echo "❌ api/config/db_config.json: MANQUANT"
          [ -d "api/documentation" ] && echo "✅ api/documentation: PRÉSENT" || echo "❌ api/documentation: MANQUANT"
          find api -name "*.php" | wc -l
          [ -d "assets" ] && echo "✅ dossier assets: PRÉSENT" || echo "❌ dossier assets: MANQUANT"
          [ -f "index.html" ] && echo "✅ fichier index.html: PRÉSENT" || echo "❌ fichier index.html: MANQUANT"
