
name: Build Application

on:
  push:
    branches: [ main ]  # Déclenche le workflow quand il y a un push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Définir cette variable pour permettre à la construction de réussir même avec des avertissements
      CI: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Récupère tout l'historique pour une meilleure compatibilité
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug - Environment & Repository
      run: |
        echo "Working directory:"
        pwd
        echo "Repository contents:"
        ls -la
        echo "Node & NPM versions:"
        node -v
        npm -v
        echo "Package.json content:"
        cat package.json
    
    - name: Install dependencies
      run: npm ci
      
    - name: Update caniuse-lite
      run: |
        echo "Mise à jour de caniuse-lite vers la dernière version..."
        npm install -D caniuse-lite@latest
    
    - name: Verify Vite installation
      run: |
        echo "Vérification de l'installation de Vite..."
        npx vite --version || npm list vite
        echo "Contenu du répertoire node_modules/.bin:"
        ls -la node_modules/.bin
    
    - name: Create build directories first
      run: |
        mkdir -p dist
        mkdir -p api
        echo "Created directories structure"
        ls -la
    
    - name: Build project
      run: |
        echo "Starting build process..."
        # Construction avec CI=false défini au niveau du job pour ignorer les avertissements
        npx vite build --debug
        echo "Build process completed"
    
    - name: Debug - Post build files
      run: |
        echo "Contenu du répertoire racine après build:"
        ls -la
        
        echo "Contenu du répertoire dist (s'il existe):"
        ls -la dist || echo "Le répertoire dist n'existe pas ou est inaccessible"
        
        echo "Contenu du répertoire api (s'il existe):"
        ls -la api || echo "Le répertoire api n'existe pas ou est inaccessible"
    
    - name: Copy necessary files to dist
      run: |
        # Création du répertoire api dans dist si nécessaire
        mkdir -p dist/api
        
        # Copier tous les fichiers nécessaires pour le déploiement dans dist
        cp -r api/* dist/api/ 2>/dev/null || echo "Pas de fichiers api à copier"
        cp .htaccess dist/ 2>/dev/null || echo "Pas de fichier .htaccess à copier"
    
    - name: Ensure .htaccess exists
      run: |
        if [ ! -f "dist/.htaccess" ]; then
          echo "Création du fichier .htaccess dans dist..."
          echo "# .htaccess generated by GitHub Actions" > dist/.htaccess
          echo "RewriteEngine On" >> dist/.htaccess
          echo "RewriteRule ^api/(.*)$ api/$1 [QSA,L]" >> dist/.htaccess
          echo "RewriteRule ^(?!api/).*$ index.html [QSA,L]" >> dist/.htaccess
          echo ".htaccess créé avec contenu de base:"
          cat dist/.htaccess
        else
          echo ".htaccess existe déjà dans dist:"
          cat dist/.htaccess
        fi
    
    - name: Verify final artifacts
      run: |
        echo "Structure finale des fichiers:"
        ls -la
        echo "Contenu du répertoire dist:"
        ls -la dist
        echo "Contenu du répertoire api dans dist (s'il existe):"
        ls -la dist/api || echo "Le répertoire api n'existe pas dans dist"
        echo "Vérification des fichiers dans dist/api:"
        find dist/api -type f | sort || echo "Aucun fichier trouvé dans dist/api"
        echo "Contenu du fichier .htaccess dans dist:"
        cat dist/.htaccess || echo ".htaccess n'existe pas dans dist"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: dist
