
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Ajouter des inputs optionnels ici pour rendre le bouton plus visible
    inputs:
      deploy_message:
        description: 'Message de déploiement'
        required: false
        default: 'Déploiement manuel'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Create empty directories first (handled by FTP)
      run: |
        mkdir -p dist/api
        touch dist/api/.gitkeep

    - name: Copy API files
      run: |
        mkdir -p dist/api
        cp -v api/php-system-check.php dist/api/ || echo "Attention: php-system-check.php non trouvé"
        cp -v api/php-execution-test.php dist/api/ || echo "Attention: php-execution-test.php non trouvé"
        cp -v api/phpinfo.php dist/api/ || echo "Attention: phpinfo.php non trouvé"
        cp -v api/diagnostic.php dist/api/ || echo "Attention: diagnostic.php non trouvé"
        cp -v api/info.php dist/api/ || echo "Attention: info.php non trouvé"
        # Create simple index.php file without heredoc syntax
        echo "<?php" > dist/api/index.php
        echo "// Point d'entrée principal de l'API" >> dist/api/index.php
        echo "header(\"Content-Type: application/json\");" >> dist/api/index.php
        echo "header(\"Access-Control-Allow-Origin: *\");" >> dist/api/index.php
        echo "echo json_encode([\"status\" => \"success\", \"message\" => \"API is working\"]);" >> dist/api/index.php
        echo "?>" >> dist/api/index.php

    - name: Create API directory structure
      run: |
        # Création des sous-dossiers nécessaires dans dist/api
        mkdir -p dist/api/config
        mkdir -p dist/api/controllers
        mkdir -p dist/api/middleware
        mkdir -p dist/api/models
        mkdir -p dist/api/utils
        
        # Copier les fichiers .htaccess nécessaires
        cp -v api/.htaccess dist/api/ || echo "Attention: .htaccess non trouvé"
        cp -v .htaccess dist/ || echo "Attention: .htaccess racine non trouvé"
        
        # Création de fichiers test pour s'assurer que les dossiers sont créés
        touch dist/api/config/.gitkeep
        touch dist/api/controllers/.gitkeep
        touch dist/api/middleware/.gitkeep
        touch dist/api/models/.gitkeep
        touch dist/api/utils/.gitkeep
        
        # Create test.php file for basic testing
        echo "<?php" > dist/api/test.php
        echo "header(\"Content-Type: application/json\");" >> dist/api/test.php
        echo "header(\"Access-Control-Allow-Origin: *\");" >> dist/api/test.php
        echo "echo json_encode([\"status\" => \"success\", \"test\" => \"ok\", \"timestamp\" => time()]);" >> dist/api/test.php
        echo "?>" >> dist/api/test.php

    - name: Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
