
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_message:
        description: 'Message de déploiement'
        required: false
        default: 'Déploiement manuel'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Create directories on server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        include: |
          mkdir-commands.txt
        dangerous-clean-slate: false
        protocol: ftp
        port: 21
        timeout: 120000
        server-dir: "./"
        dry-run: false
      env:
        FTP_PASSIVE_MODE: "true"
        
    - name: Create mkdir commands file
      run: |
        echo "mkdir -p assets" > mkdir-commands.txt
        echo "mkdir -p api" >> mkdir-commands.txt
        echo "mkdir -p api/config" >> mkdir-commands.txt
        echo "mkdir -p api/controllers" >> mkdir-commands.txt
        echo "mkdir -p api/middleware" >> mkdir-commands.txt
        echo "mkdir -p api/models" >> mkdir-commands.txt
        echo "mkdir -p api/utils" >> mkdir-commands.txt
        echo "mkdir -p public/lovable-uploads" >> mkdir-commands.txt

    - name: Execute commands on FTP server
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: |
          mkdir -p assets
          mkdir -p api
          mkdir -p api/config
          mkdir -p api/controllers
          mkdir -p api/middleware
          mkdir -p api/models
          mkdir -p api/utils
          mkdir -p public
          mkdir -p public/lovable-uploads

    - name: List dist content for debugging
      run: |
        echo "==== Listing dist directory ===="
        ls -la dist/
        echo "==== Listing dist/assets directory ===="
        ls -la dist/assets/

    - name: Deploy to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        dangerous-clean-slate: false
        protocol: ftp
        port: 21
        timeout: 120000
        server-dir: "./"
        log-level: "verbose"
