
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Ceci permet de déclencher manuellement le workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build React App
      run: npm run build
      
    - name: Create complete directory structure
      run: |
        mkdir -p dist/api/config
        mkdir -p dist/api/controllers
        mkdir -p dist/api/middleware
        mkdir -p dist/api/models
        mkdir -p dist/api/utils
        mkdir -p dist/public/lovable-uploads

    - name: Copy API files
      run: |
        cp -v api/index.php dist/api/ || echo "index.php not found"
        cp -v api/.htaccess dist/api/ || echo ".htaccess not found"
        # Ajoutez d'autres fichiers API nécessaires ici

    - name: Sync to Infomaniak
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          *.log
        log-level: verbose
        timeout: 120000
        dry-run: false
