
name: Build Application

on:
  push:
    branches: [ main ]  # Déclenche le workflow quand il y a un push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug - Environment & Repository
      run: |
        echo "Working directory:"
        pwd
        echo "Repository contents:"
        ls -la
        echo "Node & NPM versions:"
        node -v
        npm -v
        echo "Package.json content:"
        cat package.json
    
    - name: Install dependencies
      run: npm ci
      continue-on-error: true
    
    - name: Create build directories first
      run: |
        mkdir -p dist
        mkdir -p api
        echo "Created directories structure"
        ls -la
    
    - name: Build project - with fallback
      run: |
        echo "Starting build process..."
        npm run build || echo "Build process had issues, continuing with workflow"
        echo "Build process completed"
    
    - name: Debug - Post build files
      run: |
        echo "Contenu du répertoire racine après build:"
        ls -la
        
        echo "Contenu du répertoire dist (s'il existe):"
        ls -la dist || echo "Le répertoire dist n'existe pas ou est inaccessible"
        
        echo "Contenu du répertoire api (s'il existe):"
        ls -la api || echo "Le répertoire api n'existe pas ou est inaccessible"
    
    - name: Create fallback content if build failed
      run: |
        # Vérifier si le build a généré du contenu, sinon créer des fichiers minimaux
        if [ ! -d "dist" ] || [ ! "$(ls -A dist 2>/dev/null)" ]; then
          echo "Création de contenu minimal pour dist..."
          mkdir -p dist
          echo "<html><body><h1>Site en maintenance</h1></body></html>" > dist/index.html
        fi
        
        if [ ! -d "api" ] || [ ! "$(ls -A api 2>/dev/null)" ]; then
          echo "Vérification du contenu api..."
          mkdir -p api
          if [ ! -f "api/index.php" ]; then
            echo "<?php echo 'API en maintenance'; ?>" > api/index.php
          fi
        fi
    
    - name: Ensure .htaccess exists
      run: |
        if [ ! -f ".htaccess" ]; then
          echo "Création du fichier .htaccess..."
          echo "# .htaccess generated by GitHub Actions" > .htaccess
          echo "RewriteEngine On" >> .htaccess
          echo "RewriteRule ^api/(.*)$ api/$1 [QSA,L]" >> .htaccess
          echo "RewriteRule ^(?!api/).*$ index.html [QSA,L]" >> .htaccess
          echo ".htaccess créé avec contenu de base:"
          cat .htaccess
        else
          echo ".htaccess existe déjà:"
          cat .htaccess
        fi
    
    - name: Verify final artifacts
      run: |
        echo "Structure finale des fichiers:"
        ls -la
        echo "Contenu du répertoire dist:"
        ls -la dist
        echo "Contenu du répertoire api:"
        ls -la api
        echo "Contenu du fichier .htaccess:"
        cat .htaccess
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: |
          dist
          api
          .htaccess
