
    # Dans la section "Copy API files"
    cp -v api/php-system-check.php dist/api/ || echo "Attention: php-system-check.php non trouvé"
    cp -v api/php-execution-test.php dist/api/ || echo "Attention: php-execution-test.php non trouvé"
