
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build React App
      run: npm run build
      
    - name: Prepare Full Directory Structure
      run: |
        echo "Préparation de la structure complète..."
        
        # Créer le dossier principal
        mkdir -p dist/sites/qualiopi.ch
        
        # Déplacer tous les fichiers buildés dans le bon dossier
        mv dist/* dist/sites/qualiopi.ch/ || true
        
        # Recréer le dossier dist/sites/qualiopi.ch si nécessaire
        mkdir -p dist/sites/qualiopi.ch
        
        # Copier l'API et ses fichiers cachés
        cp -R api dist/sites/qualiopi.ch/
        cp -R api/.htaccess dist/sites/qualiopi.ch/api/ || true
        cp -R api/.user.ini dist/sites/qualiopi.ch/api/ || true
        
        # Copier les fichiers de configuration racine
        cp .htaccess dist/sites/qualiopi.ch/
        
        # Créer et copier les dossiers nécessaires
        mkdir -p dist/sites/qualiopi.ch/public/lovable-uploads
        cp -R public/lovable-uploads/* dist/sites/qualiopi.ch/public/lovable-uploads/ || true
        
    - name: Debug Directory Structure
      run: |
        echo "Structure finale avant déploiement:"
        tree dist/sites/qualiopi.ch || ls -R dist/sites/qualiopi.ch
        
    - name: Sync full dist folder to Infomaniak server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          package.json
          package-lock.json
          tsconfig*.json
          *.log
        log-level: verbose
        timeout: 120000
        dry-run: false

    - name: Post-deployment verification
      run: |
        echo "Déploiement terminé. Vérification de la structure:"
        curl -v "https://qualiopi.ch/" || echo "Vérification du site échouée"
        curl -v "https://qualiopi.ch/api/diagnostic.php" || echo "Vérification de l'API échouée"

