
name: Deploy to Infomaniak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build React App
      run: npm run build
      
    - name: Debug build output
      run: |
        echo "============== Debugging build output =============="
        echo "Liste des fichiers dans dist:"
        ls -la dist/
        echo "Liste des fichiers assets:"
        ls -la dist/assets/ || echo "Dossier assets non trouvé"
        echo "Contenu de index.html:"
        cat dist/index.html || echo "Fichier index.html non trouvé"

    - name: Prepare deployment directory
      run: |
        # Création des dossiers nécessaires
        mkdir -p deploy/assets
        mkdir -p deploy/api/config
        mkdir -p deploy/api/services
        mkdir -p deploy/api/controllers
        mkdir -p deploy/api/models
        mkdir -p deploy/api/models/traits
        mkdir -p deploy/api/middleware
        mkdir -p deploy/api/operations
        mkdir -p deploy/api/utils
        mkdir -p deploy/public/lovable-uploads
        
        # Vérification des fichiers JS et CSS critiques dans dist/assets
        echo "Vérification des fichiers JS et CSS principaux..."
        MAIN_JS=$(find dist/assets -name "main*.js" | head -n 1)
        INDEX_JS=$(find dist/assets -name "index*.js" | head -n 1)
        MAIN_CSS=$(find dist/assets -name "*.css" | head -n 1)
        
        if [ -z "$MAIN_JS" ] && [ -z "$INDEX_JS" ]; then
          echo "ATTENTION: Aucun fichier main.js ou index.js trouvé dans dist/assets!"
        else
          echo "Fichier JS principal trouvé: ${MAIN_JS:-$INDEX_JS}"
        fi
        
        if [ -z "$MAIN_CSS" ]; then
          echo "ATTENTION: Aucun fichier CSS trouvé dans dist/assets!"
        else
          echo "Fichier CSS principal trouvé: $MAIN_CSS"
        fi
        
        # Copie du contenu du dossier dist à la racine du déploiement
        echo "Copie de index.html à la racine..."
        cp dist/index.html deploy/
        
        # Copie des fichiers assets avec vérification et feedback
        echo "Copie des assets..."
        mkdir -p deploy/assets
        if [ -d "dist/assets" ]; then
          cp -rv dist/assets/* deploy/assets/
          echo "Nombre de fichiers copiés dans deploy/assets: $(find deploy/assets -type f | wc -l)"
        else
          echo "ERREUR: Le dossier dist/assets n'existe pas!"
        fi
        
        # Créer des fichiers statiques de fallback si nécessaire
        if [ ! -f "deploy/assets/main.js" ] && [ ! -f "deploy/assets/index.js" ]; then
          echo "Création d'un fichier index.js de fallback..."
          echo "console.log('Fichier de fallback chargé. Veuillez vider le cache du navigateur.');" > deploy/assets/index.js
        fi
        
        # Création d'un backup des assets pour référence
        mkdir -p deploy/dist/assets
        cp -r dist/assets/* deploy/dist/assets/ || echo "Aucun fichier à copier pour le backup"
        
        # Copie des autres fichiers nécessaires
        cp .htaccess deploy/ || echo "Fichier .htaccess non trouvé"
        cp fix-assets-auto.php deploy/ || echo "Fichier fix-assets-auto.php non trouvé"
        
        # Vérifier la présence du fichier assets/index.js (important)
        if [ ! -f "deploy/assets/index.js" ] && [ -f "src/assets/index.js" ]; then
          echo "Copie manuelle du fichier src/assets/index.js vers deploy/assets/..."
          cp src/assets/index.js deploy/assets/
        fi
        
        # Copie des fichiers de l'API
        if [ -d "api" ]; then
          echo "Copie des fichiers API..."
          cp -r api/* deploy/api/
        else
          echo "Dossier API non trouvé"
        fi
        
        # Copie des uploads si existants
        if [ -d "public/lovable-uploads" ]; then
          echo "Copie des uploads..."
          cp -r public/lovable-uploads/* deploy/public/lovable-uploads/ || echo "Copie des uploads échouée"
        else
          echo "Dossier uploads non trouvé"
        fi
        
        # Vérification finale des assets
        echo "Contenu final du dossier assets:"
        ls -la deploy/assets/
        
        echo "Structure du dossier de déploiement:"
        find deploy -type f | sort | head -n 20

    - name: Sync to Infomaniak server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy/
        server-dir: /sites/qualiopi.ch/
        dangerous-clean-slate: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/api-tools/**
          **/api/admin/**
          **/api/documentation/**
          README.md
          package.json
          package-lock.json
        log-level: verbose
        timeout: 120000
    
    - name: Run Fix-Assets Script (if server supports it)
      run: |
        echo "Exécution du script de réparation des assets via curl..."
        curl -s "${{ secrets.SITE_URL }}/fix-assets-auto.php" || echo "Échec de l'exécution du script de réparation"
        echo "Script de réparation terminé"

    - name: Clean up
      run: |
        rm -rf deploy
        rm -rf dist
